name: vaccine-design
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - nextflow=22.10.6
  
  # Python packages
  - biopython=1.79
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - requests=2.29.0